In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv('smsspamcollection.tsv',sep='\t')

In [4]:
df.head()

label                                            message  length  punct
0   ham  Go until jurong point, crazy.. Available only ...     111      9
1   ham                      Ok lar... Joking wif u oni...      29      6
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...     155      6
3   ham  U dun say so early hor... U c already then say...      49      6
4   ham  Nah I don't think he goes to usf, he lives aro...      61      2

In [5]:
df.isnull().sum() #No missing Value

label      0
message    0
length     0
punct      0
dtype: int64

In [6]:
len(df)

5572

In [7]:
df['label'].unique()

array(['ham', 'spam'], dtype=object)

In [8]:
df['label'].value_counts()

ham     4825
spam     747
Name: label, dtype: int64

In [9]:
from sklearn.model_selection import train_test_split

In [11]:
# X feature data
X = df[['length','punct']]
# y is our label
y = df['label']

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [13]:
from sklearn.linear_model import LogisticRegression

In [15]:
lr_model = LogisticRegression(solver='lbfgs')

In [16]:
lr_model.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='lbfgs',
          tol=0.0001, verbose=0, warm_start=False)

In [17]:
from sklearn import metrics

In [19]:
prediction = lr_model.predict(X_test)

In [21]:
print(metrics.confusion_matrix(y_test,prediction))

[[1404   44]
 [ 219    5]]


In [24]:
df = pd.DataFrame(metrics.confusion_matrix(y_test,prediction),index=['ham','spam'],columns=['ham','spam'])

In [25]:
df

ham  spam
ham   1404    44
spam   219     5

In [27]:
print(metrics.classification_report(y_test,prediction))

              precision    recall  f1-score   support

         ham       0.87      0.97      0.91      1448
        spam       0.10      0.02      0.04       224

   micro avg       0.84      0.84      0.84      1672
   macro avg       0.48      0.50      0.48      1672
weighted avg       0.76      0.84      0.80      1672



In [28]:
print(metrics.accuracy_score(y_test,prediction))

0.8427033492822966


In [29]:
from sklearn.naive_bayes import MultinomialNB

In [30]:
nb_model = MultinomialNB()
nb_model.fit(X_train,y_train)
predic = nb_model.predict(X_test)
print(metrics.confusion_matrix(y_test,predic))

[[1438   10]
 [ 224    0]]


In [31]:
print(metrics.classification_report(y_test,predic))

              precision    recall  f1-score   support

         ham       0.87      0.99      0.92      1448
        spam       0.00      0.00      0.00       224

   micro avg       0.86      0.86      0.86      1672
   macro avg       0.43      0.50      0.46      1672
weighted avg       0.75      0.86      0.80      1672



In [32]:
from sklearn.svm import SVC

svc_model = SVC()
svc_model.fit(X_train,y_train)
predic = svc_model.predict(X_test)
print(metrics.confusion_matrix(y_test,predic))

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


[[1373   75]
 [ 121  103]]


In [33]:
print(metrics.classification_report(y_test,predic))

              precision    recall  f1-score   support

         ham       0.92      0.95      0.93      1448
        spam       0.58      0.46      0.51       224

   micro avg       0.88      0.88      0.88      1672
   macro avg       0.75      0.70      0.72      1672
weighted avg       0.87      0.88      0.88      1672

